version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: fortify-app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
    networks:
      - fortify-net
    user: "${UID:-1000}:${GID:-1000}"

  nginx:
    image: nginx:latest
    container_name: fortify-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./backend/storage:/var/www/html/storage
    depends_on:
      - app
    networks:
      - fortify-net

  mysql:
    image: mysql:8.0
    container_name: fortify-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fortify-net

networks:
  fortify-net:


volumes:
  mysql-data:
