name: Deploy to VPS

on:
  push:
    branches:
      - main  # mainブランチへのpushで起動

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_DEPLOY_KEY }}
          port: 22
          script: |
            cd /apps/fortify-docker-app
            git pull
            docker compose up -d --build
